import math
import sys
from pathlib import Path

import pygame as pg

# Make the src/ root importable so the shared map generator can be loaded.
BASE_DIR = Path(__file__).resolve().parents[2]
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

import config
from entities.player import Player
from screens import Screen
from ui import draw_label
from shared.tilemap import (
    TILE_GROUND,
    TILE_KEY,
    TILE_POTION,
    TILE_POWER,
    TILE_STONE,
    TILE_TREASURE,
    TILE_WALL,
    TILE_WATER,
    generate_map,
)


class GameScreen(Screen):
    def __init__(self, manager, client, game_state):
        self.manager = manager
        self.client = client
        self.game_state = game_state

        self.hud_font = pg.font.SysFont(config.FONT_NAME, config.FONT_SIZE_SMALL)
        self.tile_size = max(32, config.TILE_SIZE - 16)
        self.map_width = 100
        self.map_height = 80

        self.player = Player(game_state)
        self.projectiles = []
        self.bullet_image = self._load_bullet_sprite()
        self.tile_images = self._load_tile_images()
        self.world = generate_map(
            self.map_width,
            self.map_height,
            profile=self.game_state.get("profile", {}),
            seed=self.game_state.get("player_id"),
        )
        self.player.world_x = self.world.player_spawn[1] * self.tile_size
        self.player.world_y = self.world.player_spawn[0] * self.tile_size

    def handle_event(self, event):
        if event.type == pg.QUIT:
            sys.exit(0)
        if event.type == pg.KEYDOWN:
            if event.key == pg.K_p:
                self.manager.switch_to(config.SCREEN_PAUSE)
            if event.key == pg.K_e:
                self.manager.switch_to(config.SCREEN_INVENTORY)

        if event.type == pg.MOUSEBUTTONDOWN and event.button == 1:
            mouse_pos = pg.mouse.get_pos()
            self.player.handle_attack(mouse_pos)

            # Spawn projectile from the player's center
            start_x = self.player.world_x + self.player.size // 2
            start_y = self.player.world_y + self.player.size // 2
            dx = mouse_pos[0] - (config.SCREEN_WIDTH // 2)
            dy = mouse_pos[1] - (config.SCREEN_HEIGHT // 2)
            self._create_projectile(start_x, start_y, dx, dy)

    def update(self, dt):
        keys = pg.key.get_pressed()
        class_key = self.game_state.get("player_class", config.DEFAULT_CLASS)
        stats = config.PLAYER_CLASSES.get(class_key, {})
        self.player.speed = stats.get("speed", config.PLAYER_DEFAULT_SPEED)

        # Run multiplier
        if keys[pg.K_LSHIFT] or keys[pg.K_RSHIFT]:
            self.player.speed *= config.PLAYER_RUN_SPEED_MULTIPLIER

        self.player.update(dt, keys)
        self.world.update(dt)
        self.client.poll_events()

        # Update bullets
        for p in self.projectiles[:]:
            p['x'] += p['dx']
            p['y'] += p['dy']
            p['dist'] += config.PROJECTILE_SPEED
            if p['dist'] > config.PROJECTILE_MAX_DISTANCE:
                self.projectiles.remove(p)

    def draw(self, surface):
        surface.fill((10, 10, 18))

        # === CAMERA CENTER ===
        cam_x = self.player.world_x - config.SCREEN_WIDTH // 2 + self.player.size // 2
        cam_y = self.player.world_y - config.SCREEN_HEIGHT // 2 + self.player.size // 2

        tile_size = self.tile_size
        start_col = max(0, int(cam_x // tile_size) - 1)
        start_row = max(0, int(cam_y // tile_size) - 1)
        end_col = min(self.world.width, start_col + (config.SCREEN_WIDTH // tile_size) + 3)
        end_row = min(self.world.height, start_row + (config.SCREEN_HEIGHT // tile_size) + 3)

        for row in range(start_row, end_row):
            for col in range(start_col, end_col):
                screen_x = col * tile_size - cam_x
                screen_y = row * tile_size - cam_y
                tile_id = self.world.tile_at(row, col)
                self._draw_tile(surface, tile_id, pg.Rect(screen_x, screen_y, tile_size, tile_size))

        # Door to the next level
        self._draw_door(surface, cam_x, cam_y)

        # Treasure chest
        self._draw_treasure(surface, cam_x, cam_y)

        # Items generated by BFS validation
        for item in self.world.items:
            self._draw_item(surface, item, cam_x, cam_y)

        # Blue-circle monsters
        for monster in self.world.monsters:
            self._draw_monster(surface, monster, cam_x, cam_y)

        # Draw Player (centered)
        self.player.draw(surface)

        # Draw Projectiles
        for p in self.projectiles:
            sx = p['x'] - cam_x
            sy = p['y'] - cam_y
            rotated = pg.transform.rotate(self.bullet_image, p['angle'])
            rect = rotated.get_rect(center=(int(sx), int(sy)))
            surface.blit(rotated, rect)

        # HUD
        draw_label(surface,
            "WASD/Arrows: Move | Shift: Run | Mouse: Shoot | P: Pause | E: Inventory",
            (10, config.SCREEN_HEIGHT - 30),
            font=self.hud_font, color=config.COLOR_GRAY)

    def _create_projectile(self, start_x, start_y, dx, dy):
        length = math.hypot(dx, dy) or 1
        self.projectiles.append({
            'x': start_x,
            'y': start_y,
            'dx': (dx / length) * config.PROJECTILE_SPEED,
            'dy': (dy / length) * config.PROJECTILE_SPEED,
            'dist': 0,
            'angle': math.degrees(math.atan2(dy, dx))
        })

    def _load_bullet_sprite(self):
        bullet_path = Path(__file__).resolve().parent.parent / "assets" / "players" / "gunman" / "bullet.png"
        try:
            image = pg.image.load(str(bullet_path)).convert_alpha()
        except Exception:
            image = pg.Surface((16, 16), pg.SRCALPHA)
            pg.draw.circle(image, (255, 220, 90), (8, 8), 6)
        return pg.transform.scale(image, (12, 12))

    def _load_tile_images(self):
        tile_root = Path(__file__).resolve().parent.parent.parent / "shared" / "tiles" / "environment"
        sprite_paths = {
            TILE_GROUND: tile_root / "ground.png",
            TILE_WALL: tile_root / "wall.png",
            TILE_STONE: tile_root / "bigrock.png",
            TILE_WATER: tile_root / "water.png",
            TILE_KEY: tile_root / "keys_1.png",
            TILE_POTION: tile_root / "keys_2.png",
            TILE_POWER: tile_root / "keys_2.png",
        }

        fallback_colors = {
            TILE_GROUND: (54, 58, 44),
            TILE_WALL: (92, 88, 82),
            TILE_STONE: (62, 62, 68),
            TILE_WATER: (40, 95, 160),
            TILE_KEY: (210, 190, 50),
            TILE_POTION: (70, 180, 110),
            TILE_POWER: (180, 90, 210),
        }

        images = {}
        for tile_id, path in sprite_paths.items():
            try:
                image = pg.image.load(str(path)).convert_alpha()
                images[tile_id] = pg.transform.scale(image, (self.tile_size, self.tile_size))
            except Exception:
                surface = pg.Surface((self.tile_size, self.tile_size), pg.SRCALPHA)
                surface.fill(fallback_colors[tile_id])
                images[tile_id] = surface

        return images

    def _draw_tile(self, surface, tile_id, rect):
        image = self.tile_images.get(tile_id)
        if tile_id == TILE_TREASURE:
            pg.draw.rect(surface, (170, 35, 35), rect.inflate(-4, -4), border_radius=5)
            pg.draw.rect(surface, (245, 220, 120), rect.inflate(-8, -8), 2, border_radius=4)
            return

        if image is not None:
            surface.blit(image, rect)
            if tile_id == TILE_KEY:
                pg.draw.circle(surface, (255, 230, 90), rect.center, max(3, rect.width // 5))
            elif tile_id == TILE_POTION:
                pg.draw.circle(surface, (80, 220, 120), rect.center, max(3, rect.width // 5))
            elif tile_id == TILE_POWER:
                pg.draw.circle(surface, (200, 110, 255), rect.center, max(3, rect.width // 5))
        else:
            pg.draw.rect(surface, (45, 45, 35), rect)

    def _draw_treasure(self, surface, cam_x, cam_y):
        row, col = self.world.treasure_position
        x = col * self.tile_size - cam_x
        y = row * self.tile_size - cam_y
        rect = pg.Rect(x, y, self.tile_size, self.tile_size)
        pg.draw.rect(surface, (190, 40, 40), rect.inflate(-6, -6), border_radius=4)
        pg.draw.rect(surface, (255, 220, 110), rect.inflate(-12, -12), 2, border_radius=3)

    def _draw_door(self, surface, cam_x, cam_y):
        row, col = self.world.door_position
        x = col * self.tile_size - cam_x
        y = row * self.tile_size - cam_y
        rect = pg.Rect(x + 8, y + 6, self.tile_size - 16, self.tile_size - 12)
        pg.draw.rect(surface, (145, 110, 55), rect, border_radius=4)
        pg.draw.rect(surface, (255, 210, 90), rect, 2, border_radius=4)

    def _draw_item(self, surface, item, cam_x, cam_y):
        row = item.get("row", 0)
        col = item.get("col", 0)
        kind = item.get("kind")
        x = col * self.tile_size - cam_x
        y = row * self.tile_size - cam_y
        center = (int(x + self.tile_size / 2), int(y + self.tile_size / 2))
        radius = max(4, self.tile_size // 5)

        if kind == TILE_KEY:
            pg.draw.circle(surface, (255, 225, 90), center, radius)
        elif kind == TILE_POTION:
            pg.draw.circle(surface, (80, 220, 120), center, radius)
        elif kind == TILE_POWER:
            pg.draw.circle(surface, (200, 120, 255), center, radius)

    def _draw_monster(self, surface, monster, cam_x, cam_y):
        row = monster.get("row", 0)
        col = monster.get("col", 0)
        guarding = monster.get("guarding", False)
        x = int(col * self.tile_size - cam_x + self.tile_size / 2)
        y = int(row * self.tile_size - cam_y + self.tile_size / 2)
        radius = max(8, self.tile_size // 3)
        fill = (52, 120, 230) if not guarding else (35, 90, 210)
        outline = (200, 230, 255)
        pg.draw.circle(surface, fill, (x, y), radius)
        pg.draw.circle(surface, outline, (x, y), radius, 2)