from __future__ import annotations

from pathlib import Path


TILE_WALL = 0
TILE_TRAP = 1
TILE_FLOOR = 2
TILE_WATER = 3
TILE_TREASURE = 4
TILE_BASIC_SCROLL = 5
TILE_KEY = 6
TILE_RARE_SCROLL = 7
TILE_LAVA = 8

WALKABLE_TILES = (TILE_FLOOR, TILE_WATER, TILE_TREASURE, TILE_BASIC_SCROLL, TILE_KEY, TILE_RARE_SCROLL, TILE_LAVA)
SOLID_TILES = (TILE_WALL,)

SECTOR_COUNT = 3
DEFAULT_MAP_WIDTH = 81
DEFAULT_MAP_HEIGHT = 81
DEFAULT_POPULATION_SIZE = 8
DEFAULT_GENERATIONS = 4

TILES_ROOT = Path(__file__).resolve().parents[1] / "tiles"
ENVIRONMENT_ROOT = TILES_ROOT / "environment"
ITEM_ROOT = TILES_ROOT / "items"
MONSTER_ROOT = TILES_ROOT / "monster"
