# Game constants
TILE_SIZE = 48
SCREEN_WIDTH = 16 * TILE_SIZE  # 768
SCREEN_HEIGHT = 12 * TILE_SIZE  # 576
FPS = 60

# Tile types
TILE_WALL = 0
TILE_STONE = 1
TILE_GROUND = 2
TILE_WATER = 3

# Player defaults
PLAYER_START_X = 96
PLAYER_START_Y = 96
PLAYER_DEFAULT_LIFE = 300
PLAYER_DEFAULT_SPEED = 3
PLAYER_DEFAULT_STAMINA = 200
PLAYER_DEFAULT_MANA = 200
PLAYER_DEFAULT_POWER = 100
PLAYER_DEFAULT_LIFE_REGEN_RATE = 0.1  # per second
PLAYER_DEFAULT_STAMINA_REGEN_RATE = 0.1  # per second
PLAYER_DEFAULT_MANA_REGEN_RATE = 0.1  # per second
PLAYER_DEFAULT_POWER_REGEN_RATE = 0.1  # per second
PLAYER_DEFAULT_ATTACK_RANGE = 75

# Mage defaults
MAGE_DEFAULT_LIFE = 300
MAGE_DEFAULT_SPEED = 2.5
MAGE_DEFAULT_STAMINA = 100
MAGE_DEFAULT_MANA = 250
MAGE_DEFAULT_ATTACK_RANGE = 75

# Melee defaults
MELEE_DEFAULT_LIFE = 500
MELEE_DEFAULT_SPEED = 3.0
MELEE_DEFAULT_STAMINA = 350
MELEE_DEFAULT_POWER = 200

FIGHTER_DEFAULT_LIFE = 450
FIGHTER_DEFAULT_SPEED = 3.0
FIGHTER_DEFAULT_POWER = 200
FIGHTER_DEFAULT_ATTACK_RANGE = 50

ARCHER_DEFAULT_LIFE = 350
ARCHER_DEFAULT_SPEED = 3.5
ARCHER_DEFAULT_POWER = 150
ARCHER_DEFAULT_ATTACK_RANGE = 100

# MONSTER defaults
MONSTER_DEFAULT_LIFE = 500
MONSTER_DEFAULT_SPEED = 2.2
MONSTER_ATTACK_RANGE = 150
MONSTER_CHASE_RANGE = 250
MONSTER_ATTACK_SPEED = 7.0

# Projectile defaults
PROJECTILE_SPEED = 8.0
PROJECTILE_MAX_DISTANCE = 500
FIRE_COOLDOWN_MS = 250